### ISSUE TITLE
Program crash upon maximising the window 

### ISSUE THREAD

**Issue by MHAcoustics** [openPSTD/openPSTD#115]
Version OpenPSTD-2.0.297-win64 crashes when maximising the window of openPSTD to the screen size.

**Comment by micfort** [comment]
I have tried to replicate this problem, but I can reproduce the steps. some questions:
* Is a file loaded yet?
* Have you run a simulation yet?
* Have you done any other actions?

**Comment by saitrik** [comment]
This problem does not occur for me, in version OpenPSTD-2.0.298-win64 . I tested for two cases,
 a) Created a domain and ran the simulation in full screen size
b) Loaded a simulation file that's already run and maximised the screen size.

In both cases, the program did not crash.

**Comment by micfort** [comment]
I think this has been solved
