### ISSUE TITLE
Boundary conditon - boundary mismatch

### ISSUE THREAD

**Issue by saitrik** [openPSTD/openPSTD#116]
If I have my absorption coefficient = 0 at the bottom and an absorption coefficient =1 in other boundaries (left, top and center),  I would expect to see reflections from the bottom and no reflections from the other three sides. Accordingly the colors of the boundary also suggests the same, black in the bottom to show completely rigid boundary and light green at top, left and center. But when I visualise the simulation using the frame-slider,  I don't see any reflection from the bottom. Instead I see reflection from the top, which is the other way round. I have attached some pictures to explain this.

![reflection4](https://cloud.githubusercontent.com/assets/19469774/19971693/0fe61120-a1e0-11e6-8735-613623827dff.PNG)

![reflection5](https://cloud.githubusercontent.com/assets/19469774/19971708/1ca2d83a-a1e0-11e6-96ba-e7646498ca2c.PNG)

See that the bottom boundary is colored black but there is no reflection visibile. Whereas in the second picture, you can see reflection from the top.

So, I assume that the domain is visualised upside down, or in other words, the top is the bottom and bottom is the top. So is it possible to have the color of the boundary point to the correct boundary as well, because this could be quite confusing?

**Comment by Louisvh** [comment]
This was actually a problem deep inside the kernel. It was swapped because of some confusion on whether the coefficient was a reflection or absorption parameter. It should be fixed now.
