### ISSUE TITLE
OpenPSTD-2.0.299-win64 not working in Windows

### ISSUE THREAD

**Issue by saitrik** [openPSTD/openPSTD#117]
The gui opens but does not display anything. This is the message I see (might be an OpenGL issue).

![errorlog](https://cloud.githubusercontent.com/assets/19469774/20630373/d5d9f9d0-b330-11e6-9e5e-704233c7b6f9.PNG)

**Comment by micfort** [comment]
fixed in 7bc5fa169e9a49881e9fab62420d17d977e8a0d9
also added test the shaders against the GLSL reference compiler from khronos. So the shaders should work in every implementation
