### ISSUE TITLE
Program error upon opening new file

### ISSUE THREAD

**Issue by MHAcoustics** [openPSTD/openPSTD#118]
I downloaded version 2.0.3.22, open the program and created a new file. The log in the background then keeps showing messages on invalid things. I can run a calculation but do not get any result.

**Comment by saitrik** [comment]
As Maarten had posted, I cannot visualise the results in the GUI as I move the slider ( the frames). But, I can export the result in HDF5 format and can process it in Matlab.  So I guess it's a visualisation problem.

**Comment by saitrik** [comment]
Vendor: Intel
Renderer: Intel(R) HD Graphics 4600
Version: 3.3.0 - Build 9.18.10.3324
Shading language version: 3.30 - Build 9.18.10.3324
OpenGL version: 3.3
------------------------------------------------------
=Viewer2D:: f->glDisable(GL_CULL_FACE)
1280: invalid enumerant
QOpenGLShader::compile(Fragment): WARNING: 0:1: '#version' :  version number dep
recated in OGL 3.0 forward compatible context driver
ERROR: 3:10: 'texture2D' : function is removed in Forward Compatibile context
ERROR: 3:10: 'texture2D' : no matching overloaded function found (using implicit
 conversion)
ERROR: 3:10: 'r' :  field selection requires structure, vector, or matrix on lef
t hand side


*** Problematic Fragment shader source code ***
//////////////////////////////////////////////////////////////////////////
//                                                                      //
// This file is part of openPSTD.                                       //
//                                                                      //
// openPSTD is free software: you can redistribute it and/or modify     //
// it under the terms of the GNU General Public License as published by //
// the Free Software Foundation, either version 3 of the License, or    //
// (at your option) any later version.                                  //
//                                                                      //
// openPSTD is distributed in the hope that it will be useful,          //
// but WITHOUT ANY WARRANTY; without even the implied warranty of       //
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        //
// GNU General Public License for more details.                         //
//                                                                      //
// You should have received a copy of the GNU General Public License    //
// along with openPSTD.  If not, see <http://www.gnu.org/licenses/>.    //
//                                                                      //
//////////////////////////////////////////////////////////////////////////

#version 330
#define lowp
#define mediump
#define highp
#line 21

uniform vec4 color;
in vec2 v_texcoord;
uniform sampler2D font;

out vec4 screen_color;

void main()
{
    float value = texture2D(font, v_texcoord).r;
    screen_color = vec4(color.rgb, color.a*value);
}
***
QOpenGLShader::compile(Fragment): WARNING: 0:1: '#version' :  version number dep
recated in OGL 3.0 forward compatible context driver
ERROR: 3:13: 'texture2D' : function is removed in Forward Compatibile context
ERROR: 3:13: 'texture2D' : no matching overloaded function found (using implicit
 conversion)
ERROR: 3:13: 'r' :  field selection requires structure, vector, or matrix on lef
t hand side


*** Problematic Fragment shader source code ***
//////////////////////////////////////////////////////////////////////////
//                                                                      //
// This file is part of openPSTD.                                       //
//                                                                      //
// openPSTD is free software: you can redistribute it and/or modify     //
// it under the terms of the GNU General Public License as published by //
// the Free Software Foundation, either version 3 of the License, or    //
// (at your option) any later version.                                  //
//                                                                      //
// openPSTD is distributed in the hope that it will be useful,          //
// but WITHOUT ANY WARRANTY; without even the implied warranty of       //
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        //
// GNU General Public License for more details.                         //
//                                                                      //
// You should have received a copy of the GNU General Public License    //
// along with openPSTD.  If not, see <http://www.gnu.org/licenses/>.    //
//                                                                      //
//////////////////////////////////////////////////////////////////////////

#version 330
#define lowp
#define mediump
#define highp
#line 21

uniform float vmin;
uniform float vmax;

in vec2 v_texcoord;

uniform sampler2D values;

out vec4 color;

void main()
{
    float value = texture2D(values, v_texcoord).r;

    if(value < vmin)
    {
        value = vmin;
    }
    else if(value > vmax)
    {
        value = vmax;
    }

    value = (value-vmin)/(vmax-vmin)*2-1;
    float valueAbs = abs(value);
    if(valueAbs != 0)
        valueAbs = pow(valueAbs, 0.5);
    if(0 < value)
    {
        color = vec4(valueAbs, 0, 0, 1);
    }
    else
    {
        color = vec4(0, 0, valueAbs, 1);
    }

}
***


The fragment of code above is being displayed in the shell window, which could be related to the problem.

**Comment by micfort** [comment]
This problem should be fixed in build 2.0.329, commit ac854f1. Is it possible that this is verified?

**Comment by saitrik** [comment]
Yes, I will verify and get back to you.

**Comment by saitrik** [comment]
The visualization works, with respect to visualizing the simulation run (propagation of waves). But the grids don't match the discretization spacing.  For example, please refer the picture below.

![capture](https://cloud.githubusercontent.com/assets/19469774/21984020/4271bf74-dbf4-11e6-8e11-f6968b927808.PNG)

The grid spacing is 0,2 but what it shows does not correspond to 0,2. It works till 0,5 but for anything below that, the grid shows a larger grid spacing. I'm also copying the error I get in the shell, below.

Vendor: Intel
Renderer: Intel(R) HD Graphics 4600
Version: 3.3.0 - Build 9.18.10.3324
Shading language version: 3.30 - Build 9.18.10.3324
OpenGL version: 3.3
------------------------------------------------------
=Viewer2D:: f->glDisable(GL_CULL_FACE)
1280: invalid enumerant
------------------------------------------------------
=Viewer2D:: this->layers[0]->UpdateScene
1280: invalid enumerant

**Comment by micfort** [comment]
Try to zoom in. If you are too far out, lines between some elements will be skipped. If this is not done then the visualization will only show lines and not any interesting results. 

The original issue is solved, so I will close this issue. if something comes up, you have to open a new issue.

**Comment by saitrik** [comment]
It works ! I can see them now when I zoom.
