### ISSUE TITLE
Restructure c++ source code files

### ISSUE THREAD

**Issue by 0mar** [openPSTD/openPSTD#23]
Will be done this Friday, so commit everything on time, then we have no merge conflicts.

The following will be done
- Add namespaces for the GUI, CLI and shared namespace
- Move the GUI, CLI and shared files to separate directories
- Add a shared library for the CLI and GUI functions that they share
- Move tests to a separate directory

**Comment by micfort** [comment]
anything else that needs to be ordered friday??

**Comment by 0mar** [comment]
Can't think of anything. I'm good to go!

**Comment by micfort** [comment]
PSTDFile will also be split up into 2 parts, 1 for the kernel(configuration) and 1 for the CLI/GUI(the file format it self

**Comment by micfort** [comment]
- Also split up the cmake file
- Removed old code
- Changed the namespacing in Kernel(everything is now in OpenPSTD and the 5 seperate targets in their designated namespaces)
- Renamed files so it's clearer and less useless info on screen
