### ISSUE TITLE
Calculations still running

### ISSUE THREAD

**Issue by micfort** [openPSTD/openPSTD#74]
If I exit the GUI, calculation are still running somewhere, I believe this should be stopped as well.

**Comment by micfort** [comment]
I can't reproduce this bug.
How do you notice that the calculations are still running??

**Comment by Louisvh** [comment]
On the Linux version this does not seem to be a problem. @micfort, could you check if it shows up in the Windows version? If not we should probably close this.

**Comment by micfort** [comment]
does not show up
