### ISSUE TITLE
Reading HDF5 in matlab

### ISSUE THREAD

**Issue by saitrik** [openPSTD/openPSTD#86]
Hi,
       I have been trying to run a test case with a basic single domain geometry and settings. The simulation runs fine. I export it as HDF5 to a file called testoutput.h5.  These are the commands I use to read the output file in matlab. 

cd('C:\Users\STRIKOOTAM\Documents\OpenPSTD\OpenPSTD\OpenPSTD-2.0.264-win64');
info=h5read('testoutput.h5','/frame/1/5');

That is, I go into the output folder and try to read the data of frame 5 of domain 1. And I get this error:

**Error using h5readc
Unable to open file. Filename may be corrupt or have unsupported characters.

Error in h5read (line 58)
[data,var_class] = h5readc(Filename,Dataset,start,count,stride);**

Am I making a mistake while importing the file? Or has it got to do with something in the simulation?

**Comment by micfort** [comment]
I'm assuming that you have a single domain?
If so, then you have the datasetname wrong. (the datasetname is the second parameter in h5read)
This should be '/frame/0/5'

It is also possible to list all the items inside a H5 file, see http://nl.mathworks.com/help/matlab/ref/h5disp.html

**Comment by saitrik** [comment]
I tried with this:

info=h5read('testoutput.h5','/frame/0/5');

I get the same error as before. When I try to display the contents of the file using,
h5disp('testoutput.h5');

This is the error I get:

Error using h5infoc
Unable to open file. Filename may be corrupt or have unsupported characters.

Error in h5info (line 74)
hinfo = h5infoc(filename,location);

Error in h5disp>display_hdf5 (line 68)
hinfo = h5info(options.Filename,options.Location);

Error in h5disp (line 48)
display_hdf5(options);

Error in saioutput (line 3)
h5disp('testoutput.h5');
  
This is the geometry :
http://postimg.org/image/pe5o5mwjf/

The spacial step is 0.5 m and time step is 0.000735 s. So total number of frames is 1360.

**Comment by micfort** [comment]
Could you save the PSTD file and send me the PSTD file and the H5 file to me. That way I can test it.
Maybe it is a bug in the export functionality

**Comment by saitrik** [comment]
[Testcase.zip](https://github.com/openPSTD/openPSTD/files/286392/Testcase.zip)

In this zip file, you can find the pstd file named Testcase.pstd and the exported output testoutput.h5. Thanks.

**Comment by micfort** [comment]
I have checked just now.
I only get the error when OpenPSTD is still open, if i first close the application and then open the H5 file in matlab, i get no error. This is why the bug never showed up in my tests.

**Comment by micfort** [comment]
It was happening because the groups weren't closed of the h5 file. The HDF5 framework has a feature that it delayed the close of file while the groups were still open, so that way if you opened the H5 file in matlab while OpenPSTD was still running the file was not yet closed by OpenPSTD and matlab gave an error. 

This is solved in built 279 (so version 2.0.279).

**Comment by saitrik** [comment]
As you said, the HDF5 import in matlab seems to be working fine, with respect to reading pressure field in the domain at every frame.  But when I try to read the impulse response at specific receivers, there seems to be no data.  

For example, 

R=h5read('testoutput5.h5','/receiver/0')

And there seems to be no data in R

R =

     []

whereas, 

F=h5read('testoutput5.h5','/frame/0/100')

works fine. 

when I try to see the contents of the output file, this is what h5disp('testoutput5.h5' )shows. 

![h5disp](https://cloud.githubusercontent.com/assets/19469774/16011335/4fdb71ce-3185-11e6-8e49-6fba6da838f1.PNG)


Since my pstd and output files are large, I'm sending a picture of the domain below. 
![testcase5 pstd](https://cloud.githubusercontent.com/assets/19469774/16010974/d3a1535e-3183-11e6-9d44-97ff6e64cbf3.PNG)

**Comment by micfort** [comment]
The kernel does not produce any receiver data yet, that's why it isn't in the exported file.
Issue is created for this. #87

**Comment by hala3** [comment]
hi, i want to generate a hdf5 file but i have this problem wen i run the file

Error using h5infoc
Unable to open file. Filename may be corrupt or have unsupported characters.

Error in h5info (line 74)
hinfo = h5infoc(filename,location);

Error in h5disp>display_hdf5 (line 68)
hinfo = h5info(options.Filename,options.Location);

Error in h5disp (line 48)
display_hdf5(options);

Error in generate_hdf5 (line 55)
h5disp('train.h5');
