### ISSUE TITLE
Program crash: new file

### ISSUE THREAD

**Issue by MHAcoustics** [openPSTD/openPSTD#93]
When I run a calculation, stop it and thereafter open a file, the program crashes.

**Comment by micfort** [comment]
Can't reproduce this error. the following steps are taken:
1. I have created 2 files, with no simulation data.
2. I opened 1 file, and then run the simulation
3. then stopped the simulation
4. Opened the other file
5. Program did not crash

I have also tried variants on it
* step 4: i created a second file in place of opened a file
* between step 3 and 4: i save the simulation data
* between step 3 and 4: I move the frame slider to show another frame, that isn't in the second file.

With these variants, the application did not crash at my end.
Did you take more steps??

**Comment by MHAcoustics** [comment]
I tried your 5 steps, the program does not crash any longer.
